name: Basic Deployment and Swap

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: myBPcalcualator
  AZURE_WEBAPP_PACKAGE_PATH: 'publish'

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Build and Publish Web App
        run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: Deploy to Azure Staging Slot
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: staging
          publish-profile: ${{ secrets.STAGING_AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  check_staging:
    needs: deploy_to_staging
    runs-on: ubuntu-latest
    steps:
      - name: Check Staging URL Response
        run: |
          response=$(curl --write-out '%{http_code}' --silent --output /dev/null https://mybpcalcualator-staging.azurewebsites.net)
          if [ "$response" -ne 200 ]; then
            echo "Staging environment did not return a 200 OK response."
            exit 1
          fi

  swap_slots:
    needs: check_staging
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Swap Staging and Production Slots
        run: az webapp deployment slot swap -n ${{ env.AZURE_WEBAPP_NAME }} -g MyResourceGroup --slot staging --target-slot production
