name: Build_Test_Deploy_Blue/Green

env:
  AZURE_WEBAPP_NAME: myBPcalcualator
  AZURE_WEBAPP_PACKAGE_PATH: 'publish'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

on:
  workflow_dispatch:
  # Uncomment the following lines if you want to trigger the workflow on push or pull request to master
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

permissions:
  id-token: write
  contents: read
  checks: write
  actions: read

jobs:
  Build_and_Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Build for Release
        run: dotnet build --configuration Release
      - name: Run unit tests
        run: dotnet test BP_UnitTest/BP_UnitTest.csproj --no-restore --collect "Code coverage" -l:trx
      - name: Publish Unit Test Results
        uses: dorny/test-reporter@v1
        with:
          name: MS Tests
          path: '**.trx'
          reporter: 'dotnet-trx'
      - name: Run Acceptance Tests
        run: dotnet test BDDtesting/BDDtesting.csproj --verbosity normal -l:trx
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=bogo80
            -Dsonar.projectKey=Bogo80_CA1Asigment
            -Dsonar.python.coverage.reportPaths=coverage.xml

  deploy_test_blue_green:
    needs: Build_and_Test
    runs-on: windows-latest
    environment:
      name: staging
      url: https://mybpcalcualator-staging.azurewebsites.net
    steps:
      - uses: actions/checkout@v4
      - name: Publish web app
        run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp
      - name: Run Azure webapp deploy action using publish profile credentials
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.STAGING_AZURE_WEBAPP_PUBLISH_PROFILE }}
          slot-name: staging
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

  k6_performance_test:
    needs: deploy_test_blue_green
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run k6 Performance Test
        uses: k6io/action@v0.1
        with:
          filename: k6tests/perf1.js
          cloud: true
          token: ${{ secrets.K6_CLOUD_API_TOKEN }}

  swap_slots:
    needs: k6_performance_test
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Swap Staging and Production Slots
        run: |
          az webapp deployment slot swap -n myBPcalcualator -g MyResource --slot "staging" --target-slot "production"
