
# simple workflow to run k6 load test using a docker container
name: k6 BP calculator

on:
  workflow_dispatch:                  # manually triggered
jobs:
  k6_cloud_test:
    name: k6 cloud test run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run k6 cloud test
        uses: k6io/action@v0.1
        with:
          filename: k6tests/perf1.js
          cloud: true
          token: ${{ secrets.K6_CLOUD_API_TOKEN }}